image:
  name: hashicorp/terraform:1.5
  entrypoint: [""]

stages:
  - apply
  - deploy
  - test
  - destroy

apply:
  stage: apply
  before_script:
    - terraform init
  script:
    - terraform apply -auto-approve
    - terraform output -raw public_ip > public_ip.txt
    - terraform output -raw private_key > generated_key.pem
    - chmod 400 generated_key.pem
    - ls -la
  artifacts:
    paths:
      - public_ip.txt
      - generated_key.pem
      - terraform.tfstate
      - terraform.tfstate.backup

deploy_nginx:
  stage: deploy
  image: alpine:latest
  dependencies:
    - apply
  before_script:
    - apk add --no-cache openssh curl
  script:
    - |
      ls -la
      IP=$(cat public_ip.txt)
      echo "EC2 IP: $IP"
      echo "Waiting for EC2 SSH..."
      sleep 60
      ssh -o StrictHostKeyChecking=no -i generated_key.pem ubuntu@$IP \
        "docker run -d -p 80:80 nginx"

test_app:
  stage: test
  image: alpine:latest
  dependencies:
    - apply        # 👈 THIS IS THE FIX
  before_script:
    - apk add --no-cache curl
  script:
    - |
      ls -la
      IP=$(cat public_ip.txt)
      echo "Testing Nginx on $IP"
      sleep 20
      curl -I http://$IP

destroy:
  stage: destroy
  before_script:
    - terraform init
  script:
    - terraform destroy -auto-approve
  when: manual
